version: '2'

services:
  webapp:
    build: ./webapp
    container_name: osps-webapp
    volumes:
      - ./webapp/app/:/usr/share/nginx/html/
    ports:
      - '80:80'
    hostname: osps-webapp
    tty: true
